Repository erdos/stencil, pull requests merged in 2022-07, with the labels that each got.

#134 feat: replace fn
  docs/Functions.md
  src/stencil/functions.clj
  test/stencil/functions_test.clj
Labels: functions

#136 fix: fragments dropped environment
  src/stencil/postprocess/fragments.clj
  test/stencil/postprocess/fragments_test.clj
Labels: syntax

#135 fix: merger substring exception
  src/stencil/merger.clj
  test/stencil/merger_test.clj
Labels: syntax

#83 feat: specs
  java-src/io/github/erdos/stencil/impl/NativeEvaluator.java
  project.clj
  src/stencil/spec.clj
Labels: enhancement, tests
